version: '2'
services:
    bolao-mysql:
        image: mysql:5.7.20
        # volumes:
        #     - ~/volumes/jhipster/bolao/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=bolao
            - MYSQL_PASSWORD=bolao
            - MYSQL_ALLOW_EMPTY_PASSWORD=false
            - MYSQL_DATABASE=bolao_prod
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp
